version: '3'
services:
  mathkiya-server:
    build: ./mathkiya/
    environment:
      - PORT=9000
      - DB_URL=mongodb://mongo:27017
    ports:
      - 9000:9000
    volumes:
      - ./mathkiya/:/usr/app/

    # this is just to say that this service needs some other service to work. 
    # depends_on:
      # - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
       - db-data:/var/lib/mongodb/data
    expose:
      - 27017

volumes:
  db-data:
