version: '3'
services:
  mathkiya-server:
    build: ./mathkiya/
    environment:
      - PORT=9000
      - DB_URL=mongodb://mongo:27017
    ports:
      - 9000:9000
    volumes:
      - ./mathkiya/src:/usr/app/src
      
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017